language: python
python:
  - "3.9"
  - "3.10-dev"
  - "3.11-dev"
  - "nightly"
  - "pypy3"

before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install -U pytest-cov
  - pip install -U codecov

install:
  - pip install -r requirements.txt
  - pip install coveralls

script:
  - pytest
  - pytest --cov=spamdetector

after_success:
  - coveralls
