language: python
python:
  - "3.9"
  - "3.10-dev"
  - "3.11-dev"
  - "nightly"

before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install -U pytest-cov
  - pip install -U codecov

install:
  - pip install -r requirements.txt
  - pip install coveralls

script:
  - coverage run --source=smapanalyzer/ --omit=spamanalyzer/__main__.py

after_success:
  - coveralls
