language: python
python:
  - "3.9"
  - "3.10-dev"
  - "3.11-dev"
  - "nightly"

before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install -U pytest-cov
  - pip install -U codecov

install:
  - pip install -r requirements.txt
  - pip install coveralls

script:
    pytest --black --cov=./app --cov-report=term-missing

after_success:
  - COVERALLS_REPO_TOKEN=mNmroiAh09mx5ksfqNqdBRroeNECbtDOi coveralls
