language: python
python:
  - "3.9"
  - "3.10"
  - "3.11-dev"

before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install -U pytest-cov
  - pip install -U codecov

install:
  - pip install -r requirements.txt

script:
  - python -m pytest
  - python -m pytest --cov=src

after_success:
  - codecov
