# constants values used across the app
files:
  # path to the default spam words file
  # wordlist source: https://gist.github.com/prasidhda/13c9303be3cbc4228585a7f1a06040a3
  wordlist: 'assets/word_blacklist.txt'


weights:
  # headers
  has_spf: 1
  has_dkim: 0.5
  has_dmarc: 0.5
  has_mx: 0.5
  spam_words_in_subject: 0.5

  # body
  spam_words: 1
