site_name: spam-analyzer
site_description: A Python package for spam detection and analysis
site_url: https://matteospanio.github.io/spam-analyzer/

nav:
  - Home: index.md
  - Documentation:
    - Getting Started: getting_started.md
    - Installation: installation.md
    - Usage: usage.md
    - Data Analysis:
      - data_analysis/index.md
      - data_analysis/SpamAnalysis.ipynb
    - API Reference:
      - api/reference.md
      - api/utils.md
    - Contributing:
      - contrib/contributing.md
      - contrib/CODE_OF_CONDUCT.md
    - Changelog: changelog.md
    - Security: SECURITY.md

theme:
  icon:
    edit: material/pencil
    view: material/eye
  name: material
  logo: assets/images/logo_transparent.png
  favicon: assets/images/logo_transparent.png
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - toc.follow
    - navigation.top
    - navigation.path

    - search.suggest
    - search.highlight
    - search.share

    - header.autohide

    - content.tooltips
    - content.tabs.link
    - content.action.edit
    - content.code.copy
    - content.code.annotate

  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default


      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

plugins:
  - search
  - mkdocs-jupyter:
      execute: false
      include_source: True
  - mkdocstrings:
      enabled: !ENV [ENABLE_MKDOCSTRINGS, true]
      default_handler: python
      handlers:
        python:
          options:
            show_source: false
  - git-revision-date-localized:
      enable_creation_date: true
  - tags:
      enabled: !ENV [CI, false]

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/matteospanio

    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/matteo-spanio/

copyright: Copyright &copy; 2022 - 2023 Matteo Spanio
repo_url: https://github.com/matteospanio/spam-analyzer
repo_name: matteospanio/spam-analyzer

markdown_extensions:
  - abbr
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - tables
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true


extra_javascript:
  - assets/js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
