version: 2
jobs:
  build:
    docker:
      - image: cimg/python:3.10.12
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: poetry install
      - run:
          name: Run tests
          command: poetry run pytest --cov=spamanalyzer/ --cov-report=xml
      - run:
          name: Send coverage to Coveralls
          command: poetry run coveralls