version: 2
jobs:
  build:
    docker:
      - image: cimg/python:3.11.4
    environment:
        LC_ALL: C.UTF-8
        LANG: C.UTF-8
        LANGUAGE: C.UTF-8
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: poetry install
      - run:
          name: Run tests
          command: poetry run pytest --cov=spamanalyzer/ --cov-report=xml
      - run:
          name: Send coverage to Coveralls
          command: poetry run coveralls